### ISSUE TITLE
issue OS X does not support NUMA - returning NUMA node zero

### ISSUE THREAD

**Issue by thegodone** [TomHeaven/tensorflow-osx-build#5] opened 2019-01-27 15:29 UTC
when installation is done I got this message error (pytorch installation works perfectly)

here an example testcase with tensorflow-1.12.0-py27-py36-py37-cuda10-cudnn74 wheel:
python37
export PATH=/Developer/NVIDIA/CUDA-10.0/bin:$PATH
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-10.0/lib:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib/:$DYLD_LIBRARY_PATH
export CPATH=/usr/local/cuda/include:$CPATH
https://github.com/flyyufelix/DenseNet-Keras

$ python3 test_inference.py 
Using TensorFlow backend.
/Users/guillaumegodin/Downloads/DenseNet-Keras/densenet121.py:45: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (7, 7), name="conv1", strides=(2, 2), use_bias=False)`
  x = Convolution2D(nb_filter, 7, 7, subsample=(2, 2), name='conv1', bias=False)(x)
2019-01-27 16:20:03.688741: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] OS X does not support NUMA - returning NUMA node zero
2019-01-27 16:20:03.689610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GT 750M major: 3 minor: 0 memoryClockRate(GHz): 0.9255
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 16.59MiB
2019-01-27 16:20:03.689643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-27 16:20:06.003836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-27 16:20:06.003869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-27 16:20:06.003877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-27 16:20:06.005312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5 MB memory) -> physical GPU (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0, compute capability: 3.0)
Illegal instruction: 4

**Comment by TomHeaven** [comment] 2019-02-25 01:54
I'm afraid this is a bug in Tensorflow source code. You can refer to this issue for further information:
https://github.com/tensorflow/tensorflow/issues/25822

You can use Python 2.7 to avoid the problem at present.

**Comment by TomHeaven** [comment] 2019-03-26 09:03
I'm closing this issue since there is nothing more I can do.

**Closed as completed** 2019-03-26 09:03 UTC

**Comment by xlla** [comment] 2022-04-13 17:39
I think this does not a bug in Tensorflow,  in tensorflow/stream_executor/cuda/cuda_gpu_executor.cc

<pre>
#if defined(__APPLE__)
  LOG(INFO) << "OS X does not support NUMA - returning NUMA node zero";
  return 0;
</pre>
