### ISSUE TITLE
Illegal instruction: 4 when importing tensorflow

### ISSUE THREAD

**Issue by hudarsono** [TomHeaven/tensorflow-osx-build#8] opened 2019-04-11 16:24 UTC
Hi,

I tried using this build tensorflow-1.12.0-cp36-cp36m-macosx_10_12_x86_64.whl and use python 3.6.5_1 on Mac OS 10.13.6, it failed to import with : 

```
(tfgpu) MacBook-Pro:tfgpu hud$ python
Python 3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Illegal instruction: 4
```
Any idea?

**Comment by hudarsono** [comment] 2019-04-11 17:40
Update : I have tried with all 3 build of tensorflow 1.12.0 CUDA 10, and 3 python versions, all results in "Illegal instruction: 4"

**Comment by TomHeaven** [comment] 2019-04-12 00:34
Try using the lastest build tf 1.13.1. You may have met a known bug as reported  here: https://github.com/tensorflow/tensorflow/issues/25822. However, py 2.7 and py 3.6 work works fine in my mac.

**Comment by TomHeaven** [comment] 2019-04-12 00:38
@hudarsono By the way, what's your hardware configuration? Do you have a Nvidia GPU?

**Comment by hudarsono** [comment] 2019-04-21 04:36
I am on Macbook Pro 15 retina mid 2012 with NVIDIA 650M. 

I cant use tf 1.13.1 as on your release note, it doesnt support compute capability 3.0 which my gpu has.

Btw, do you think having gpu support for my card will make worthy diff in performance to pursue this forward?

**Comment by TomHeaven** [comment] 2019-04-21 07:48
Maybe you can try an older release: https://github.com/TomHeaven/tensorflow-osx-build/releases/tag/v1.10.0_cu90 or https://github.com/TomHeaven/tensorflow-osx-build/releases/tag/v1.10.0_cu90_py37 with CUDA 9.

Your display card is too old and I'm afraid it can only run small models.

**Comment by hudarsono** [comment] 2019-04-23 06:09
The problem is I couldn't get CUDA 9 to works on High Sierra 10.13.6. Only CUDA 10 works. As the CUDA runtime version that support HighSierra requires CUDA 10 I think.

**Comment by TomHeaven** [comment] 2019-04-23 07:41
@hudarsono  I will add compute compatibility 3.0 back to supported list and update the release.

**Comment by hudarsono** [comment] 2019-04-23 14:07
Many thanks, will be looking forward to try it.

**Comment by TomHeaven** [comment] 2019-04-23 16:51
Try this release: https://github.com/TomHeaven/tensorflow-osx-build/releases/tag/v1.13.1_cu100_full.

**Comment by hudarsono** [comment] 2019-04-25 14:28
Strange, it still result in illegal instruction 4. 
I noticed that when running python, it is showing : 
`(tf) MacBook-Pro:tf hud$ python
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
>>> import tensorflow
Illegal instruction: 4
(tf) MacBook-Pro:tf hud$ `

Its showing Clang 10.0.0, which is previous command line tool. I have since downgraded and clang --version already show the correct version : Apple LLVM version 8.1.0 (clang-802.0.42).  However python still show clang 10.0.0. Could it be the reason?  

Another info :   this macbook only support AVX1.0  not AVX2. Does the build require AVX2 ?

This is the error dialog  : 
`Process:               Python [618]
Path:                  /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.7.3 (3.7.3)
Code Type:             X86-64 (Native)
Parent Process:        bash [485]
Responsible:           Python [618]
User ID:               501

Date/Time:             2019-04-25 21:22:26.520 +0700
OS Version:            Mac OS X 10.13.6 (17G6030)
Report Version:        12
Anonymous UUID:        DDF3F55A-5B46-82B0-51A7-516EEFCD893D


Time Awake Since Boot: 82 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
`

**Comment by TomHeaven** [comment] 2019-04-26 07:59
I think AVX1.0 may be the cause since your old CPU may not support new instruction. You can build your own tensorflow using [tutorial](https://github.com/TomHeaven/tensorflow-osx-build/blob/master/build_instructions_1.10.md) provided in the master branch.

Use `--config=nonccl` as follows
```
bazel build --config=opt --config=nonccl  //tensorflow/tools/pip_package:build_pip_package
```
then you can skip the NCCL part in the tutorial.

**Comment by hudarsono** [comment] 2019-04-28 05:06
Ok, thanks for the help so far.

**Comment by riverflow** [comment] 2019-05-03 08:41
I am really sorry, but can't you make tensorflow 1.13.1 with bazel  "--march = westmere" option? I tried many times with Mac Pro 5,1 / High Sierra 10.3.6, but I can't make. :( 
Thanks in advance.

**Comment by riverflow** [comment] 2019-05-06 00:41
Can you please build with bazel option '--copt=-march=westmere'? I can't build latest version tensorflow for my Mac Pro 5,1. thanks in advance

**Comment by hudarsono** [comment] 2019-05-09 04:39
@TomHeaven 
On ./configure : 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: --config=nonccl

Then:
 bazel build --config=opt --config=nonccl  //tensorflow/tools/pip_package:build_pip_package

The compiler doesnt start with error  : 
ERROR: Config value nonccl is not defined in any .rc file

Any idea?

**Comment by hudarsono** [comment] 2019-05-09 18:12
Update : I have successfully built working tensorflow gpu v1.10.  Btw could you release a patch for v1.13.1? is it the same with v1.10?

**Comment by montaguegabe** [comment] 2019-05-10 04:33
I just successfully built with tensorflow v1.13.1 using the instructions included in this repo. Tricky things along the way:

1) Had to build without NCCL, and I learned this is only possible if TF_NCCL_VERSION, NCCL_INSTALL_PATH are not set, and you build with` --config=nonccl`
2) I had to integrate step 4 of https://medium.com/@mattias.arro/installing-tensorflow-1-2-from-sources-with-gpu-support-on-macos-4f2c5cab8186 regarding OpenMP

**Comment by TomHeaven** [comment] 2019-05-13 08:36
Great! I should update the tutorial but just do not have spare time. I'm closing this issue.

**Closed as completed by TomHeaven** 2019-05-13 08:36 UTC

**Comment by ShaunHolt** [comment] 2020-04-27 03:37
Just in case for anyone using Condra and running into this issue.    if you use... condra search tensorflow    .... you will find a list of tensorflows you can use.  No GPU, no avx?  No problem.  Uninstall the tensorflow you have installed.....      type in.... condra install tensorflow-mkl  .....  it has worked for me with the 2.1.0 tensorflow.... and now i can use Rasa/Tensorflow.   Hopefully this helps others too.
